### ISSUE TITLE
change CJKmainfont to 宋体 or 楷体

### ISSUE THREAD

**Issue by JLHwung** [a358003542/tangshi-sanbai-shou#1]
舒体 is not suitable for legibility, any consider on changing to 宋体 or 楷体?

**Comment by a358003542** [comment]
@JLHwung 默认的CJKmainfont是adobe 宋体，并没有用到舒体？如果你是指 `shici` 环境部分，其用的是颜体，为了表现效果，因为诗词长度都适中，所以是可以接受的。如果大段大段的文字，那么确实是应该要用宋体的。

**Comment by JLHwung** [comment]
Sorry I fail to recognize fontface.
I do concern on the fontface of `shici` environment as it is distracting me from reading the text.
Poems have been typesetted using 宋体 at least from Ming dynasty, it was proved better legibility. 颜体 does have impression at first glance, but soon it burdens as it is not designed for long time reading.

**Comment by a358003542** [comment]
@JLHwung 明天有时间我会弄下github的release，颜体版本作为一个release，然后写上一些说明吧。然后再更改为宋体，在发布一个release。毕竟有些人也只是偶尔看下，并没有长时间阅读的。

**Comment by JLHwung** [comment]
It is easy to change the font, but messy to maintain two tex file for two pdf release. Sorry I could not spare time.
Personally, I suggest use `FandolSong` as `CJKmainfont` as it is free while `Adobe Songti` is commercial.

**Comment by a358003542** [comment]
@JLHwung 不太确定 `FandolSong` 是否具有全部所需的字体符号，可能某些字不会正常显示，实际上换成 `Adobe Songti` 也需要确认一下。据我所知 `Adobe Songti` 字体符号算是很全的了，然后也是可以自由使用的，况且这里也和商业扯不上关系吧。 `FandolSong` 没接触过，你可以考虑试试，看看缺不缺字体符号。

**Comment by a358003542** [comment]
@JLHwung OK.
